#!/bin/bash

#|¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨|
#| UNIPÊ Centro Univertário de João Pessoa   |
#| Aluno: Jefferson Felix Gomes              |
#| Matrícula: 1510010879                     |
#| Email: jeffersonfelix15@hotmail.com       |
#¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨

function somar {
	read -a valor
	return $[ ${valor[0]} + ${valor[2]} ] #Utilizando o elemento 0 e 2 do array para realizar a operação
}

function sub {
	read -a valo
	return $[ ${valo[0]} - ${valo[2]} ]
}

function div {
	read -a val
	if [ ${val[2]} -eq 0 ] #Tratamento: Caso o divisor sejá igual 0 resultado será 0
	then
		echo "Digite um valor maior que zero"
	else

		return $[ ${val[0]} / ${val[2]} ]
	fi
}

function mult {
	read -a va
	return $[ ${va[0]} * ${va[2]} ]
}
